CREATE TABLE IF NOT EXISTS bronze.zenga_listings (
    id serial primary key,
    megnevezes varchar(255),
    ar varchar(50) not null,
    negyzetmeter_ar varchar(50),
    cim varchar(255),
    alapterulet varchar(50),
    telek varchar(50),
    emelet varchar(50),
    szobak_szama varchar(50),
    leiras text,
    hirdeteskod varchar(100),
    referenciaszam varchar(255),
    frissitve varchar(50),
    allapot varchar(50),
    futes varchar(50),
    epites_eve varchar(50),
    terasz varchar(50),
    energetikai_besorolas varchar(50),
    hirdeto_neve varchar(255),
    ingatlan_iroda_neve varchar(255),
    tipus varchar(50),
    szintek_szama varchar(50),
    raw_data jsonb
)