x-common-variables: &env_vars
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_DB: ${DATABASE_DB}
  ENVIRONMENT: ${ENVIRONMENT}
  LOG_LEVEL: ${LOG_LEVEL}
  S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
  S3_BUCKET: ${S3_BUCKET}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}

services:
  proxy:
    image: nginx:1.31.1-alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - api
    ports:
      - "${FE_PORT}:80"
    volumes:
      - ./deploy/proxy.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
      - exclude:/usr/src/app/node_modules

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: sh -c "./wait-for-it.sh postgres:5432 -t 30 && make runapi"
    restart: unless-stopped
    volumes:
      - ./api/db:/usr/src/app/db
      - ./api/packages:/usr/src/app/packages
      - ./api/transform:/usr/src/app/transform
      - ./api/pyproject.toml:/usr/src/app/pyproject.toml
      - ./api/Makefile:/usr/src/app/Makefile
      - .env:/usr/src/app/.env
    depends_on:
      - postgres
      - migrate      
    environment: *env_vars

  scheduler:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: sh -c "./wait-for-it.sh postgres:5432 -t 30 && ./wait-for-it.sh minio:9000 -t 30 && sleep infinity"
    restart: unless-stopped
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.ingest.schedule: ${INGESTION_SCHEDULE}
      ofelia.job-exec.ingest.command: "make runingest"
      ofelia.job-exec.transform.schedule: ${TRANSFORM_SCHEDULE}
      ofelia.job-exec.transform.command: "make dbt-build"
      ofelia.job-exec.indicators.schedule: ${INDICATORS_SCHEDULE}
      ofelia.job-exec.indicators.command: "make runindicators"

      ofelia.job-exec.ingest.smtp-host: "${SMTP_HOST}"
      ofelia.job-exec.ingest.smtp-port: "${SMTP_PORT}"
      ofelia.job-exec.ingest.smtp-user: "${SMTP_USER}"
      ofelia.job-exec.ingest.smtp-password: "${SMTP_PASSWORD}"
      ofelia.job-exec.ingest.email-to: "${ALERT_EMAIL_TO}"
      ofelia.job-exec.ingest.email-from: "${ALERT_EMAIL_FROM}"
      ofelia.job-exec.ingest.mail-only-on-error: "true"

      ofelia.job-exec.transform.smtp-host: "${SMTP_HOST}"
      ofelia.job-exec.transform.smtp-port: "${SMTP_PORT}"
      ofelia.job-exec.transform.smtp-user: "${SMTP_USER}"
      ofelia.job-exec.transform.smtp-password: "${SMTP_PASSWORD}"
      ofelia.job-exec.transform.email-to: "${ALERT_EMAIL_TO}"
      ofelia.job-exec.transform.email-from: "${ALERT_EMAIL_FROM}"
      ofelia.job-exec.transform.mail-only-on-error: "true"

      ofelia.job-exec.indicators.smtp-host: "${SMTP_HOST}"
      ofelia.job-exec.indicators.smtp-port: "${SMTP_PORT}"
      ofelia.job-exec.indicators.smtp-user: "${SMTP_USER}"
      ofelia.job-exec.indicators.smtp-password: "${SMTP_PASSWORD}"
      ofelia.job-exec.indicators.email-to: "${ALERT_EMAIL_TO}"
      ofelia.job-exec.indicators.email-from: "${ALERT_EMAIL_FROM}"
      ofelia.job-exec.indicators.mail-only-on-error: "true"

    volumes:
      - ./api/db:/usr/src/app/db
      - ./api/packages:/usr/src/app/packages
      - ./api/transform:/usr/src/app/transform
      - ./api/pyproject.toml:/usr/src/app/pyproject.toml
      - ./api/Makefile:/usr/src/app/Makefile
      - .env:/usr/src/app/.env
    depends_on:
      - minio
      - postgres
      - migrate      
    environment: *env_vars

  migrate:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: sh -c "./wait-for-it.sh postgres:5432 -t 30 && make migrate"
    depends_on:
      - postgres
    volumes:
      - ./api/db:/usr/src/app/db
      - ./api/packages:/usr/src/app/packages
      - ./api/transform:/usr/src/app/transform
      - ./api/pyproject.toml:/usr/src/app/pyproject.toml
      - ./api/Makefile:/usr/src/app/Makefile
      - ./.env:/usr/src/app/.env
    environment: *env_vars

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - "${MINIO_BACKEND_PORT}:9000"
      - "${MINIO_FRONTEND_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:18.6
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
      - ./deploy/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "${POSTGRES_PORT}:5432"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - scheduler
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  exclude: