from ingatlanmizu.ingest.sources.base import Source, SeedUrl
from ingatlanmizu.ingest.sources.zenga.extract import discover, fetch_listing
from ingatlanmizu.ingest.sources.zenga.parse import parse
from ingatlanmizu.ingest.sources.zenga.load import load, hash_payload, record_observation
import random

SEED_URLS = [
    SeedUrl(county="Bács-Kiskun megye", main_type="Lakás", url="https://www.zenga.hu/bacs-kiskun-megye+elado+lakas"),
    SeedUrl(county="Bács-Kiskun megye", main_type="Ház", url="https://www.zenga.hu/bacs-kiskun-megye+elado+haz"),
    SeedUrl(county="Baranya megye", main_type="Lakás", url="https://www.zenga.hu/baranya-megye+elado+lakas"),
    SeedUrl(county="Baranya megye", main_type="Ház", url="https://www.zenga.hu/baranya-megye+elado+haz"),
    SeedUrl(county="Békés megye", main_type="Lakás", url="https://www.zenga.hu/bekes-megye+elado+lakas"),
    SeedUrl(county="Békés megye", main_type="Ház", url="https://www.zenga.hu/bekes-megye+elado+haz"),
    SeedUrl(county="Borsod-Abaúj-Zemplén megye", main_type="Lakás", url="https://www.zenga.hu/borsod-abauj-zemplen-megye+elado+lakas"),
    SeedUrl(county="Borsod-Abaúj-Zemplén megye", main_type="Ház", url="https://www.zenga.hu/borsod-abauj-zemplen-megye+elado+haz"),
    SeedUrl(county="Csongrád megye", main_type="Lakás", url="https://www.zenga.hu/csongrad-megye+elado+lakas"),
    SeedUrl(county="Csongrád megye", main_type="Ház", url="https://www.zenga.hu/csongrad-megye+elado+haz"),
    SeedUrl(county="Fejér megye", main_type="Lakás", url="https://www.zenga.hu/fejer-megye+elado+lakas"),
    SeedUrl(county="Fejér megye", main_type="Ház", url="https://www.zenga.hu/fejer-megye+elado+haz"),
    SeedUrl(county="Győr-Moson-Sopron megye", main_type="Lakás", url="https://www.zenga.hu/gyor-moson-sopron-megye+elado+lakas"),
    SeedUrl(county="Győr-Moson-Sopron megye", main_type="Ház", url="https://www.zenga.hu/gyor-moson-sopron-megye+elado+haz"),
    SeedUrl(county="Hajdú-Bihar megye", main_type="Lakás", url="https://www.zenga.hu/hajdu-bihar-megye+elado+lakas"),
    SeedUrl(county="Hajdú-Bihar megye", main_type="Ház", url="https://www.zenga.hu/hajdu-bihar-megye+elado+haz"),
    SeedUrl(county="Heves megye", main_type="Lakás", url="https://www.zenga.hu/heves-megye+elado+lakas"),
    SeedUrl(county="Heves megye", main_type="Ház", url="https://www.zenga.hu/heves-megye+elado+haz"),
    SeedUrl(county="Jász-Nagykun-Szolnok megye", main_type="Lakás", url="https://www.zenga.hu/jasz-nagykun-szolnok-megye+elado+lakas"),
    SeedUrl(county="Jász-Nagykun-Szolnok megye", main_type="Ház", url="https://www.zenga.hu/jasz-nagykun-szolnok-megye+elado+haz"),
    SeedUrl(county="Komárom-Esztergom megye", main_type="Lakás", url="https://www.zenga.hu/komarom-esztergom-megye+elado+lakas"),
    SeedUrl(county="Komárom-Esztergom megye", main_type="Ház", url="https://www.zenga.hu/komarom-esztergom-megye+elado+haz"),
    SeedUrl(county="Nógrád megye", main_type="Lakás", url="https://www.zenga.hu/nograd-megye+elado+lakas"),
    SeedUrl(county="Nógrád megye", main_type="Ház", url="https://www.zenga.hu/nograd-megye+elado+haz"),
    SeedUrl(county="Pest megye", main_type="Lakás", url="https://www.zenga.hu/pest-megye+elado+lakas"),
    SeedUrl(county="Pest megye", main_type="Ház", url="https://www.zenga.hu/pest-megye+elado+haz"),
    SeedUrl(county="Somogy megye", main_type="Lakás", url="https://www.zenga.hu/somogy-megye+elado+lakas"),
    SeedUrl(county="Somogy megye", main_type="Ház", url="https://www.zenga.hu/somogy-megye+elado+haz"),
    SeedUrl(county="Szabolcs-Szatmár-Bereg megye", main_type="Lakás", url="https://www.zenga.hu/szabolcs-szatmar-bereg-megye+elado+lakas"),
    SeedUrl(county="Szabolcs-Szatmár-Bereg megye", main_type="Ház", url="https://www.zenga.hu/szabolcs-szatmar-bereg-megye+elado+haz"),
    SeedUrl(county="Tolna megye", main_type="Lakás", url="https://www.zenga.hu/tolna-megye+elado+lakas"),
    SeedUrl(county="Tolna megye", main_type="Ház", url="https://www.zenga.hu/tolna-megye+elado+haz"),
    SeedUrl(county="Vas megye", main_type="Lakás", url="https://www.zenga.hu/vas-megye+elado+lakas"),
    SeedUrl(county="Vas megye", main_type="Ház", url="https://www.zenga.hu/vas-megye+elado+haz"),
    SeedUrl(county="Veszprém megye", main_type="Lakás", url="https://www.zenga.hu/veszprem-megye+elado+lakas"),
    SeedUrl(county="Veszprém megye", main_type="Ház", url="https://www.zenga.hu/veszprem-megye+elado+haz"),
    SeedUrl(county="Zala megye", main_type="Lakás", url="https://www.zenga.hu/zala-megye+elado+lakas"),
    SeedUrl(county="Zala megye", main_type="Ház", url="https://www.zenga.hu/zala-megye+elado+haz"),

    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-i-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-i-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-ii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-ii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-iii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-iii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-iv-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-iv-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-v-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-v-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-vi-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-vi-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-vii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-vii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-viii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-viii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-ix-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-ix-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-x-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-x-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xi-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xi-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xiii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xiii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xiv-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xiv-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xv-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xv-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xvi-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xvi-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xvii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xvii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xviii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xviii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xix-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xix-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xx-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xx-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xxi-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xxi-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xxii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xxii-kerulet+elado+haz"),
    SeedUrl(county="Budapest", main_type="Lakás", url="https://www.zenga.hu/budapest-xxiii-kerulet+elado+lakas"),
    SeedUrl(county="Budapest", main_type="Ház",    url="https://www.zenga.hu/budapest-xxiii-kerulet+elado+haz"),
]

def _random_urls(n: int) -> list[SeedUrl]:
    urls = []
    for i in range(0, n):
        rand = random.randint(0, len(SEED_URLS)-1)
        urls.append(SEED_URLS[rand])
    
    return urls

SOURCE = Source(
    name="zenga",
    seed_urls=_random_urls(2),
    discover=discover,
    fetch_listing=fetch_listing,
    parse=parse,
    load=load,
    hash_payload=hash_payload,
    record_observation=record_observation,
)